# Workflow file for this run
name: Stage-C1 Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.abc'
      - 'class/*'
      - 'language/*'
      - '**/*.txt'
  workflow_dispatch:

jobs:
  Lint:
    uses: ./github/workflows/Lint.yaml